# Generated by Django 3.1.7 on 2021-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20210524_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coverImage',
            field=models.ImageField(null=True, upload_to='product/images'),
        ),
    ]
