# Generated by Django 3.2.3 on 2021-05-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_auto_20210525_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coverImage',
            field=models.ImageField(null=True, upload_to='product/images'),
        ),
    ]
