# Generated by Django 3.2.3 on 2021-06-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_product_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='displayName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
