# Generated by Django 3.2.3 on 2021-06-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_product_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=419),
        ),
    ]
